// Shared by scripts/gen-error-codes.mjs and scripts/verify-spec.mjs so both
// derive src/error-codes.ts from the same rendering logic.

/** Sorted, de-duplicated codes from the spec's x-error-code-registry. */
export function registryCodes(spec) {
  const codes = spec['x-error-code-registry'].map((entry) => entry.code);
  return [...new Set(codes)].sort();
}

/** Renders the exact contents of src/error-codes.ts for the given spec. */
export function renderErrorCodes(spec) {
  const codes = registryCodes(spec);
  const entries = codes.map((code) => `  '${code}',`).join('\n');
  return `// Generated by scripts/gen-error-codes.mjs from test/fixtures/openapi.json.
// Do not edit by hand — run \`npm run gen:error-codes\` to refresh.

export const ERROR_CODES = [
${entries}
] as const;

export type ErrorCode = (typeof ERROR_CODES)[number];
`;
}
