// Shared by scripts/sync-spec.mjs and scripts/verify-spec.mjs: renders
// src/webhook-events.ts from the OpenAPI `webhooks` section, so the SDK's
// event types are GO-KIT's public event registry at the locked ref.
const REF = '#/components/schemas/';

const refName = (ref) => ref.slice(REF.length);
const pascal = (type) =>
  type
    .split(/[._]/)
    .map((p) => p[0].toUpperCase() + p.slice(1))
    .join('');

function tsType(schema, deps) {
  if (schema.$ref) {
    deps.add(refName(schema.$ref));
    return refName(schema.$ref);
  }
  if (schema.enum)
    return schema.enum.map((v) => (typeof v === 'string' ? `'${v}'` : String(v))).join(' | ');
  switch (schema.type) {
    case 'string':
      return 'string';
    case 'integer':
    case 'number':
      return 'number';
    case 'boolean':
      return 'boolean';
    case 'array':
      return `${tsType(schema.items ?? {}, deps)}[]`;
    case 'object':
      return objectBody(schema, deps);
    default:
      return 'unknown';
  }
}

function objectBody(schema, deps) {
  const props = Object.entries(schema.properties ?? {});
  if (props.length === 0) return 'Record<string, unknown>';
  const required = new Set(schema.required ?? []);
  const lines = props.map(([name, p]) => {
    const doc = p.description ? `  /** ${p.description} */\n` : '';
    return `${doc}  ${name}${required.has(name) ? '' : '?'}: ${tsType(p, deps)};`;
  });
  return `{\n${lines.join('\n')}\n}`;
}

/** Renders the exact contents of src/webhook-events.ts for the given spec. */
export function renderWebhookEvents(spec) {
  const hooks = spec.webhooks ?? {};
  const types = Object.keys(hooks).sort();
  if (types.length === 0) {
    throw new Error('openapi.json has no webhooks section; sync a GO-KIT ref with envelope v1');
  }
  const schemas = spec.components.schemas;
  const deps = new Set(['FlowTrigger']);
  const events = types.map((type) => {
    const post = hooks[type].post;
    const envelope = schemas[refName(post.requestBody.content['application/json'].schema.$ref)];
    const data = tsType(envelope.properties.data, deps);
    const trigger = envelope.properties.trigger
      ? `\n  trigger: ${tsType(envelope.properties.trigger, deps)};`
      : '';
    const name = `${pascal(type)}Event`;
    return {
      type,
      name,
      block: `/** ${post.description ?? type} */\nexport interface ${name} extends EnvelopeBase<'${type}'> {\n  data: ${data};${trigger}\n}`,
    };
  });
  const components = new Map();
  const queue = [...deps];
  while (queue.length > 0) {
    const name = queue.shift();
    if (components.has(name)) continue;
    const schema = schemas[name];
    const local = new Set();
    const isInterface = schema.type === 'object' && Object.keys(schema.properties ?? {}).length > 0;
    const body = tsType(schema, local);
    components.set(
      name,
      isInterface ? `export interface ${name} ${body}` : `export type ${name} = ${body};`,
    );
    queue.push(...local);
  }
  const componentBlocks = [...components.keys()].sort().map((n) => components.get(n));
  return `// Generated by scripts/sync-spec.mjs from test/fixtures/openapi.json (webhooks).
// Do not edit by hand — run \`npm run sync-spec\` to refresh.

interface EnvelopeBase<T extends string> {
  /** Event id: identical for every endpoint and every retry. */
  id: string;
  type: T;
  api_version: 'v1';
  /** When the event happened, RFC3339 UTC. */
  created_at: string;
  org_id: string;
}

${componentBlocks.join('\n\n')}

${events.map((e) => e.block).join('\n\n')}

export type KnownWebhookEnvelope =
${events.map((e) => `  | ${e.name}`).join('\n')};

/** An event type this SDK version does not know yet. Acknowledge it; do not fail. */
export interface UnknownWebhookEnvelope extends EnvelopeBase<string> {
  data: Record<string, unknown>;
  trigger?: FlowTrigger;
}

export type WebhookEnvelope = KnownWebhookEnvelope | UnknownWebhookEnvelope;

export const WEBHOOK_EVENT_TYPES = [
${types.map((t) => `  '${t}',`).join('\n')}
] as const;

export type WebhookEventType = (typeof WEBHOOK_EVENT_TYPES)[number];

/** Narrows an envelope to one known event type. */
export function isWebhookEvent<T extends WebhookEventType>(
  event: WebhookEnvelope,
  type: T,
): event is Extract<KnownWebhookEnvelope, { type: T }> {
  return event.type === type;
}
`;
}
