// Generated by scripts/sync-spec.mjs from test/fixtures/openapi.json (webhooks).
// Do not edit by hand — run `npm run sync-spec` to refresh.

interface EnvelopeBase<T extends string> {
  /** Event id: identical for every endpoint and every retry. */
  id: string;
  type: T;
  api_version: 'v1';
  /** When the event happened, RFC3339 UTC. */
  created_at: string;
  org_id: string;
}

export interface BankCreditData {
  /** Amount in VND, an integer exact up to 2^53-1 end to end (projection, wire, and SDK types) */
  amount: number;
  /** Bank code, lowercase (ocb, mb, ...) */
  bank: string;
  /** The bank's own reference for the transaction */
  bank_ref: string;
  /** Transfer memo as the payer wrote it; untrusted text */
  description: string;
  /** When the bank booked the transaction */
  transaction_date: string;
  /** Transaction id; equal to the envelope id */
  transaction_id: string;
  /** Virtual account the credit landed in; absent when none matched */
  va_number?: string;
}

export interface BankDebitData {
  /** Amount in VND, an integer exact up to 2^53-1 end to end (projection, wire, and SDK types) */
  amount: number;
  /** Bank code, lowercase (ocb, mb, ...) */
  bank: string;
  /** The bank's own reference for the transaction */
  bank_ref: string;
  /** Transfer memo; untrusted text */
  description: string;
  /** When the bank booked the transaction */
  transaction_date: string;
  /** Transaction id; equal to the envelope id */
  transaction_id: string;
}

export interface BankPaymentMatchedData {
  /** Amount in VND, an integer exact up to 2^53-1 end to end (projection, wire, and SDK types) */
  amount: number;
  /** The intent's payment code */
  code: string;
  /** The payment intent the credit settled */
  intent_id: string;
  /** The credit that settled it */
  transaction_id: string;
}

export interface FlowTrigger {
  /** The flow that produced this output */
  flow_id: string;
  /** Id of the event that triggered the flow */
  id: string;
  /** Type of the triggering event */
  type: string;
}

export interface MemberInvitedData {
  /** The invitee's email address */
  email: string;
}

export type OrgCreatedData = Record<string, unknown>;

export interface OrgQuotaExceededData {
  /** The period's limit, an integer exact up to 2^53-1 end to end */
  limit: number;
  /** First day AFTER the period (Asia/Ho_Chi_Minh) */
  period_end_exclusive: string;
  /** First day of the period (Asia/Ho_Chi_Minh) */
  period_start: string;
  resource: 'bank_transactions';
  /** Usage when the notice fired, an integer exact up to 2^53-1 end to end */
  used: number;
}

export interface SubscriptionEventData {
  /** End of the current period; absent when none */
  period_end?: string;
  /** Start of the current period; absent when none */
  period_start?: string;
  plan_id: string;
  plan_name: string;
  status: 'pending_payment' | 'active' | 'past_due' | 'expired' | 'cancelled';
  subscription_id: string;
}

/** Money arrived in a linked bank account. */
export interface BankCreditEvent extends EnvelopeBase<'bank.credit'> {
  data: BankCreditData;
}

/** Money left a linked bank account (only banks that push debits emit it). Opt-in: a subscribe-all endpoint does not receive it. */
export interface BankDebitEvent extends EnvelopeBase<'bank.debit'> {
  data: BankDebitData;
}

/** An incoming credit settled a payment intent. */
export interface BankPaymentMatchedEvent extends EnvelopeBase<'bank.payment.matched'> {
  data: BankPaymentMatchedData;
}

/** A flow built this delivery's data from the triggering event. data is whatever the flow produced; trigger names the source event and the flow. */
export interface FlowOutputEvent extends EnvelopeBase<'flow.output'> {
  data: Record<string, unknown>;
  trigger: FlowTrigger;
}

/** The organization was created. */
export interface OrgCreatedEvent extends EnvelopeBase<'org.created'> {
  data: OrgCreatedData;
}

/** Someone was invited to join the organization. */
export interface OrgMemberInvitedEvent extends EnvelopeBase<'org.member_invited'> {
  data: MemberInvitedData;
}

/** The organization used up its monthly transaction quota; deliveries of bank events pause until the next period or an upgrade. */
export interface OrgQuotaExceededEvent extends EnvelopeBase<'org.quota_exceeded'> {
  data: OrgQuotaExceededData;
}

/** A subscription became active. */
export interface SubscriptionActivatedEvent extends EnvelopeBase<'subscription.activated'> {
  data: SubscriptionEventData;
}

/** A subscription was cancelled. */
export interface SubscriptionCancelledEvent extends EnvelopeBase<'subscription.cancelled'> {
  data: SubscriptionEventData;
}

/** A subscription ended unpaid. */
export interface SubscriptionExpiredEvent extends EnvelopeBase<'subscription.expired'> {
  data: SubscriptionEventData;
}

/** A subscription renewal is unpaid. */
export interface SubscriptionPastDueEvent extends EnvelopeBase<'subscription.past_due'> {
  data: SubscriptionEventData;
}

/** A subscription was renewed for another period. */
export interface SubscriptionRenewedEvent extends EnvelopeBase<'subscription.renewed'> {
  data: SubscriptionEventData;
}

export type KnownWebhookEnvelope =
  | BankCreditEvent
  | BankDebitEvent
  | BankPaymentMatchedEvent
  | FlowOutputEvent
  | OrgCreatedEvent
  | OrgMemberInvitedEvent
  | OrgQuotaExceededEvent
  | SubscriptionActivatedEvent
  | SubscriptionCancelledEvent
  | SubscriptionExpiredEvent
  | SubscriptionPastDueEvent
  | SubscriptionRenewedEvent;

/** An event type this SDK version does not know yet. Acknowledge it; do not fail. */
export interface UnknownWebhookEnvelope extends EnvelopeBase<string> {
  data: Record<string, unknown>;
  trigger?: FlowTrigger;
}

export type WebhookEnvelope = KnownWebhookEnvelope | UnknownWebhookEnvelope;

export const WEBHOOK_EVENT_TYPES = [
  'bank.credit',
  'bank.debit',
  'bank.payment.matched',
  'flow.output',
  'org.created',
  'org.member_invited',
  'org.quota_exceeded',
  'subscription.activated',
  'subscription.cancelled',
  'subscription.expired',
  'subscription.past_due',
  'subscription.renewed',
] as const;

export type WebhookEventType = (typeof WEBHOOK_EVENT_TYPES)[number];

/** Narrows an envelope to one known event type. */
export function isWebhookEvent<T extends WebhookEventType>(
  event: WebhookEnvelope,
  type: T,
): event is Extract<KnownWebhookEnvelope, { type: T }> {
  return event.type === type;
}
